### ISSUE TITLE
Opening new note when creating it.

### ISSUE THREAD

**Issue by Iippa** [Skrifa/Skrifa#15]
Hello all,

I have been using Skrifa for a few months now and it is great! Thank you to everyone contributing. 

I'm using Ubuntu 16.04 and I noticed that when creating a new note it does not automatically open it. Is this a bug, something you can change in settings or done on purpose? 

I have not found a setting where I could change this and I can't think of a way when it would be useful to create a new note and not to open it right away.

**Comment by Hyuchia** [comment]
Hi there! This was simply an overlooked behavior and code has been recently added to the master branch (#16) that will cause the note to open when created. This new feature will be available on the next release :)
